spring:
  profiles:
    active: dev
  servlet:
    multipart:
      #设置文件大小
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB

#Mybatis
mybatis:
  #
  typealiasespackage: com.whu.toolman.entity
  #mybatis
  mapper-locations: classpath:mapper/*.xml
  #
  configuration:
    map-underscore-to-camel-case: true
