spring:
  profiles:
    active: prod
  servlet:
    multipart:
      #设置文件大小
      max-file-size: 10MB
      enabled: true
      max-request-size: 10MB

  mail:
      host: smtp.qq.com
      username: 2596105310@qq.com
      default-encoding: UTF-8
      password: qgpiogxkxfuheadj
      port: 465
      properties:
        mail:
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory

#Mybatis
mybatis:
  #
  typealiasespackage: com.whu.toolman.entity
  #mybatis
  mapper-locations: classpath:mapper/*.xml
  #
  configuration:
    map-underscore-to-camel-case: true

