spring:
  profiles:
    active: dev
#Mybatis
mybatis:
  #
  typealiasespackage: com.whu.toolman.entity
  #mybatis
  mapper-locations: classpath:mapper/*.xml
  #
  configuration:
    map-underscore-to-camel-case: true
