# application-pro.yml
variable:
  profiles : prod
server:
  port: 9050
spring:
  mvc:
    static-path-pattern: /ToolManResources/**
  resources:
    static-locations: file:/root/toolman/ToolManResources/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toolman?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

url: http://116.62.164.228:9050/ToolManResources/
filePath: /root/toolman/ToolManResources/